runtime: python39
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_APP: "app"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always